[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

# Change Mega Stone target prefix to 'agar' when selecting one of our injection targets
[[patches]]
[patches.pattern]
target = '=[SMODS Pokermon "consumables/mart1.lua"]'
position = "after"
match_indent = true
pattern = '''local prefix = target.config.center.poke_custom_prefix or "poke"'''
payload = '''if string.sub(AGAR.FAMILY_UTILS.get_injection_payload(target.config.center.key) or "", 1, 11) == 'j_agar_mega_' then prefix = "agar" end'''
